version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      workflows-toolbox:
        patterns:
          - "densestvoid/workflows*"
      github-actions:
        patterns:
          - "*"
        exclude-patterns:
          - "densestvoid/workflows*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      gomod-root:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /assets
    schedule:
      interval: weekly
      day: monday
    groups:
      npm-frontend:
        patterns:
          - "*"
