# https://taskfile.dev

version: '3'

tasks:
  build:
    dir: cmd/kroger-recipes
    cmds:
      - go build -ldflags "-w"
    env:
      GOARCH: amd64
      GOOS: linux

  deploy:
    dir: cmd/kroger-recipes
    dotenv: ['{{.ROOT_DIR}}/.env']
    cmds:
      - scp -i $SSHKEY kroger-recipes $USERNAME@$HOST:$BINPATH

  ssh:
    dotenv: ['{{.ROOT_DIR}}/.env']
    cmds:
      - ssh -i $SSHKEY $USERNAME@$HOST
  
  migration:
    cmds:
      - goose --dir migrations -s create {{.CLI_ARGS}} sql

  ci:
   cmds:
      - go vet ./...
      - go tool staticcheck ./...
      - go tool golangci-lint run ./...
      - go tool govulncheck ./...
      - go tool gosec ./...