# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cmd/kroger-recipes
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        check-latest: true

    - name: Install tools
      run: go install github.com/go-task/task/v3/cmd/task@latest

    - name: Build
      run: task build

    - name: Store artifact
      uses: actions/upload-artifact@v4
      with:
        name: binary
        path: cmd/kroger-recipes/kroger-recipes

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        check-latest: true
        
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: binary
        path: cmd/kroger-recipes/kroger-recipes

    - name: Install tools
      run: go install github.com/go-task/task/v3/cmd/task@latest

    - name: Add SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval `ssh-agent -s`
        ssh-add
        ssh-keyscan -p 22 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy
      env:
        SSHKEY: ~/.ssh/id_rsa
        HOST: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USER }}
        BINPATH: ${{ secrets.SSH_BINPATH }}
      run: task deploy
