# Integration workflow that uses the reusable Go Checks workflow
# The actual workflow logic is maintained in the workflows repository

name: Integration

on:
  pull_request:

jobs:
  go-checks:
    uses: densestvoid/workflows/.github/workflows/go-checks.yml@main
