# Integration workflow that performs Go code quality checks

name: Integration

on:
  pull_request:

jobs:
  go-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        check-latest: true

    - name: Install tools
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        go install golang.org/x/vuln/cmd/govulncheck@latest
        go install github.com/securego/gosec/v2/cmd/gosec@latest

    - name: Run all checks
      run: |
        echo "Running go vet..."
        go vet ./...
        
        echo "Running static analysis..."
        staticcheck ./...
        
        echo "Running linter..."
        golangci-lint run ./...
        
        echo "Running vulnerability check..."
        govulncheck ./...
        
        echo "Running security check..."
        gosec ./...
        
        echo "All checks completed successfully!"
